// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: debug.sql

package database

import (
	"context"
)

const resetDatabase = `-- name: ResetDatabase :exec
TRUNCATE TABLE users, cancers, protocols, refresh_tokens, logs, physicians,
protocol_eligibility_criteria, protocol_cautions, medications,
medication_prescription, protocol_treatment, medication_modifications,
protocol_precautions, protocol_ppos, tests, protocol_tests, protocol_meds,
protocol_cycles, article_references, toxicities, toxicity_grades,
protocol_tox_modifications RESTART IDENTITY CASCADE
`

func (q *Queries) ResetDatabase(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetDatabase)
	return err
}
