// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Cancer struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Code       sql.NullString
	Name       sql.NullString
	Tags       []string
	Notes      string
	TumorGroup string
}

type CancerProtocol struct {
	CancerID   uuid.UUID
	ProtocolID uuid.UUID
}

type Log struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	IpAddress string
	UserAgent string
	Action    string
}

type Protocol struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	TumorGroup string
	Code       string
	Name       string
	Tags       []string
	Notes      string
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	UserID    uuid.UUID
}

type User struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Email      string
	Password   string
	Role       string
	IsVerified bool
	DeletedAt  sql.NullTime
	DeletedBy  uuid.NullUUID
	LastActive sql.NullTime
}
