// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ArticleReference struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Title     string
	Authors   string
	Journal   string
	Year      string
	Pmid      string
	Joi       string
}

type Cancer struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Code       sql.NullString
	Name       sql.NullString
	Tags       []string
	Notes      string
	TumorGroup string
}

type CancerProtocol struct {
	CancerID   uuid.UUID
	ProtocolID uuid.UUID
}

type Log struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	IpAddress string
	UserAgent string
	Action    string
}

type Medication struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Description sql.NullString
	Category    string
}

type Physician struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	FirstName string
	LastName  string
	Email     string
	Site      string
}

type Protocol struct {
	ID                uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	TumorGroup        string
	Code              string
	Name              string
	Tags              []string
	Notes             string
	ProtocolUrl       string
	PatientHandoutUrl string
}

type ProtocolBaselineTest struct {
	ProtocolID uuid.UUID
	TestID     uuid.UUID
}

type ProtocolBaselineTestsIfNecessary struct {
	ProtocolID uuid.UUID
	TestID     uuid.UUID
}

type ProtocolBaselineTestsNonUrgent struct {
	ProtocolID uuid.UUID
	TestID     uuid.UUID
}

type ProtocolCaution struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Description string
}

type ProtocolCautionsValue struct {
	ProtocolID uuid.UUID
	CautionID  uuid.UUID
}

type ProtocolContactPhysician struct {
	ProtocolID  uuid.UUID
	PhysicianID uuid.UUID
}

type ProtocolCycle struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Cycle         string
	CycleDuration string
	ProtocolID    uuid.UUID
}

type ProtocolEligibilityCriteriaValue struct {
	ProtocolID uuid.UUID
	CriteriaID uuid.UUID
}

type ProtocolEligibilityCriterium struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Type        string
	Description string
}

type ProtocolFollowupTest struct {
	ProtocolID uuid.UUID
	TestID     uuid.UUID
}

type ProtocolFollowupTestsIfNecessary struct {
	ProtocolID uuid.UUID
	TestID     uuid.UUID
}

type ProtocolPpo struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Title      string
	Url        string
	ProtocolID uuid.UUID
}

type ProtocolPreMedicationsValue struct {
	ProtocolID      uuid.UUID
	PreMedicationID uuid.UUID
}

type ProtocolPrecaution struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Description string
}

type ProtocolPrecautionsValue struct {
	ProtocolID   uuid.UUID
	PrecautionID uuid.UUID
}

type ProtocolPremedication struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Medication uuid.UUID
	Dose       string
	Route      string
	Frequency  string
	Duration   string
	Notes      string
}

type ProtocolReferencesValue struct {
	ProtocolID  uuid.UUID
	ReferenceID uuid.UUID
}

type ProtocolSupportiveMedication struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Medication uuid.UUID
	Dose       string
	Route      string
	Frequency  string
	Duration   string
	Notes      string
}

type ProtocolSupportiveMedicationValue struct {
	ProtocolID             uuid.UUID
	SupportiveMedicationID uuid.UUID
}

type ProtocolTreatment struct {
	ID                  uuid.UUID
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Medication          uuid.UUID
	Dose                string
	Route               string
	Frequency           string
	Duration            string
	AdministrationGuide string
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	UserID    uuid.UUID
}

type Test struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Description sql.NullString
}

type ToxicityModification struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Grade       string
	Adjustement string
	ProtocolID  uuid.UUID
}

type TreatmentCyclesJunction struct {
	ProtocolTreatmentID uuid.UUID
	ProtocolCyclesID    uuid.UUID
}

type TreatmentModification struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Category    string
	Description string
	Adjustement string
	TreatmentID uuid.UUID
}

type User struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Email      string
	Password   string
	Role       string
	IsVerified bool
	DeletedAt  sql.NullTime
	DeletedBy  uuid.NullUUID
	LastActive sql.NullTime
}
