// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: protocol_treatment.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addCycleToProtocol = `-- name: AddCycleToProtocol :one
INSERT INTO protocol_cycles (protocol_id, cycle, cycle_duration)
VALUES ($1, $2, $3)
RETURNING id, created_at, updated_at, cycle, cycle_duration, protocol_id
`

type AddCycleToProtocolParams struct {
	ProtocolID    uuid.UUID
	Cycle         string
	CycleDuration string
}

func (q *Queries) AddCycleToProtocol(ctx context.Context, arg AddCycleToProtocolParams) (ProtocolCycle, error) {
	row := q.db.QueryRowContext(ctx, addCycleToProtocol, arg.ProtocolID, arg.Cycle, arg.CycleDuration)
	var i ProtocolCycle
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Cycle,
		&i.CycleDuration,
		&i.ProtocolID,
	)
	return i, err
}

const addProtocolTreatment = `-- name: AddProtocolTreatment :one
INSERT INTO protocol_treatment (medication, dose, route, frequency, duration, administration_guide)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at, medication, dose, route, frequency, duration, administration_guide
`

type AddProtocolTreatmentParams struct {
	Medication          uuid.UUID
	Dose                string
	Route               string
	Frequency           string
	Duration            string
	AdministrationGuide string
}

func (q *Queries) AddProtocolTreatment(ctx context.Context, arg AddProtocolTreatmentParams) (ProtocolTreatment, error) {
	row := q.db.QueryRowContext(ctx, addProtocolTreatment,
		arg.Medication,
		arg.Dose,
		arg.Route,
		arg.Frequency,
		arg.Duration,
		arg.AdministrationGuide,
	)
	var i ProtocolTreatment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Medication,
		&i.Dose,
		&i.Route,
		&i.Frequency,
		&i.Duration,
		&i.AdministrationGuide,
	)
	return i, err
}

const addTreatmentToCycle = `-- name: AddTreatmentToCycle :exec
INSERT INTO treatment_cycles_values (protocol_cycles_id, protocol_treatment_id)
VALUES ($1, $2)
`

type AddTreatmentToCycleParams struct {
	ProtocolCyclesID    uuid.UUID
	ProtocolTreatmentID uuid.UUID
}

func (q *Queries) AddTreatmentToCycle(ctx context.Context, arg AddTreatmentToCycleParams) error {
	_, err := q.db.ExecContext(ctx, addTreatmentToCycle, arg.ProtocolCyclesID, arg.ProtocolTreatmentID)
	return err
}

const getCycleByData = `-- name: GetCycleByData :one
SELECT id, created_at, updated_at, cycle, cycle_duration, protocol_id FROM protocol_cycles
WHERE protocol_id = $1 AND cycle = $2 AND cycle_duration = $3
`

type GetCycleByDataParams struct {
	ProtocolID    uuid.UUID
	Cycle         string
	CycleDuration string
}

func (q *Queries) GetCycleByData(ctx context.Context, arg GetCycleByDataParams) (ProtocolCycle, error) {
	row := q.db.QueryRowContext(ctx, getCycleByData, arg.ProtocolID, arg.Cycle, arg.CycleDuration)
	var i ProtocolCycle
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Cycle,
		&i.CycleDuration,
		&i.ProtocolID,
	)
	return i, err
}

const getCyclesByProtocol = `-- name: GetCyclesByProtocol :many
SELECT protocol_cycles.id, protocol_cycles.created_at, protocol_cycles.updated_at, protocol_cycles.cycle, protocol_cycles.cycle_duration, protocol_cycles.protocol_id
FROM protocol_cycles
WHERE protocol_cycles.protocol_id = $1
ORDER BY protocol_cycles.cycle ASC
`

func (q *Queries) GetCyclesByProtocol(ctx context.Context, protocolID uuid.UUID) ([]ProtocolCycle, error) {
	rows, err := q.db.QueryContext(ctx, getCyclesByProtocol, protocolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProtocolCycle
	for rows.Next() {
		var i ProtocolCycle
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Cycle,
			&i.CycleDuration,
			&i.ProtocolID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProtocolTreatmentByData = `-- name: GetProtocolTreatmentByData :one
SELECT id, created_at, updated_at, medication, dose, route, frequency, duration, administration_guide FROM protocol_treatment
WHERE medication = $1 AND dose = $2 AND route = $3 AND frequency = $4 AND duration = $5
`

type GetProtocolTreatmentByDataParams struct {
	Medication uuid.UUID
	Dose       string
	Route      string
	Frequency  string
	Duration   string
}

func (q *Queries) GetProtocolTreatmentByData(ctx context.Context, arg GetProtocolTreatmentByDataParams) (ProtocolTreatment, error) {
	row := q.db.QueryRowContext(ctx, getProtocolTreatmentByData,
		arg.Medication,
		arg.Dose,
		arg.Route,
		arg.Frequency,
		arg.Duration,
	)
	var i ProtocolTreatment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Medication,
		&i.Dose,
		&i.Route,
		&i.Frequency,
		&i.Duration,
		&i.AdministrationGuide,
	)
	return i, err
}

const getProtocolTreatmentByID = `-- name: GetProtocolTreatmentByID :one
SELECT id, created_at, updated_at, medication, dose, route, frequency, duration, administration_guide FROM protocol_treatment
WHERE id = $1
`

func (q *Queries) GetProtocolTreatmentByID(ctx context.Context, id uuid.UUID) (ProtocolTreatment, error) {
	row := q.db.QueryRowContext(ctx, getProtocolTreatmentByID, id)
	var i ProtocolTreatment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Medication,
		&i.Dose,
		&i.Route,
		&i.Frequency,
		&i.Duration,
		&i.AdministrationGuide,
	)
	return i, err
}

const getTreatmentsByCycle = `-- name: GetTreatmentsByCycle :many
SELECT protocol_treatment.id, protocol_treatment.created_at, protocol_treatment.updated_at, protocol_treatment.medication, protocol_treatment.dose, protocol_treatment.route, protocol_treatment.frequency, protocol_treatment.duration, protocol_treatment.administration_guide
FROM protocol_treatment
JOIN treatment_cycles_values ON protocol_treatment.id = treatment_cycles_values.protocol_treatment_id
WHERE treatment_cycles_values.protocol_cycles_id = $1
ORDER BY protocol_treatment.medication ASC
`

func (q *Queries) GetTreatmentsByCycle(ctx context.Context, protocolCyclesID uuid.UUID) ([]ProtocolTreatment, error) {
	rows, err := q.db.QueryContext(ctx, getTreatmentsByCycle, protocolCyclesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProtocolTreatment
	for rows.Next() {
		var i ProtocolTreatment
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Medication,
			&i.Dose,
			&i.Route,
			&i.Frequency,
			&i.Duration,
			&i.AdministrationGuide,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProtocolTreatment = `-- name: RemoveProtocolTreatment :exec
DELETE FROM protocol_treatment
WHERE id = $1
`

func (q *Queries) RemoveProtocolTreatment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeProtocolTreatment, id)
	return err
}

const removeTreatmentFromCycle = `-- name: RemoveTreatmentFromCycle :exec
DELETE FROM treatment_cycles_values
WHERE protocol_cycles_id = $1 AND protocol_treatment_id = $2
`

type RemoveTreatmentFromCycleParams struct {
	ProtocolCyclesID    uuid.UUID
	ProtocolTreatmentID uuid.UUID
}

func (q *Queries) RemoveTreatmentFromCycle(ctx context.Context, arg RemoveTreatmentFromCycleParams) error {
	_, err := q.db.ExecContext(ctx, removeTreatmentFromCycle, arg.ProtocolCyclesID, arg.ProtocolTreatmentID)
	return err
}

const updateProtocolTreatment = `-- name: UpdateProtocolTreatment :one
UPDATE protocol_treatment
SET
    updated_at = NOW(),
    medication = $2,
    dose = $3,
    route = $4,
    frequency = $5,
    duration = $6,
    administration_guide = $7
WHERE id = $1
RETURNING id, created_at, updated_at, medication, dose, route, frequency, duration, administration_guide
`

type UpdateProtocolTreatmentParams struct {
	ID                  uuid.UUID
	Medication          uuid.UUID
	Dose                string
	Route               string
	Frequency           string
	Duration            string
	AdministrationGuide string
}

func (q *Queries) UpdateProtocolTreatment(ctx context.Context, arg UpdateProtocolTreatmentParams) (ProtocolTreatment, error) {
	row := q.db.QueryRowContext(ctx, updateProtocolTreatment,
		arg.ID,
		arg.Medication,
		arg.Dose,
		arg.Route,
		arg.Frequency,
		arg.Duration,
		arg.AdministrationGuide,
	)
	var i ProtocolTreatment
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Medication,
		&i.Dose,
		&i.Route,
		&i.Frequency,
		&i.Duration,
		&i.AdministrationGuide,
	)
	return i, err
}
